#
# Copyright (C) 2021 Grakn Labs
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

config:
  version-candidate: VERSION
  dependencies:
    dependencies: [build]
    common: [build, release]
    graql: [build, release]
    protocol: [build, release]
    grabl-tracing: [build, release]
    behaviour: [build]

build:
  quality:
    filter:
      owner: graknlabs
      branch: master
    build-analysis:
      image: graknlabs-ubuntu-20.04
      command: |
        SONARCLOUD_CODE_ANALYSIS_CREDENTIAL=$SONARCLOUD_CREDENTIAL \
          bazel run @graknlabs_dependencies//tool/sonarcloud:code-analysis -- \
          --project-key=graknlabs_grakn_core \
          --branch=$GRABL_BRANCH --commit-id=$GRABL_COMMIT
    dependency-analysis:
      image: graknlabs-ubuntu-20.04
      command: |
        bazel run @graknlabs_dependencies//grabl/analysis:dependency-analysis
  correctness:
    build:
      image: graknlabs-ubuntu-20.04
      command: |
        bazel test //test/integration/docs:test-1 --test_output=streamed --runs_per_test=100
release:
  filter:
    owner: graknlabs
    branch: master
  validation:
    validate-dependencies:
      image: graknlabs-ubuntu-20.04
      command: bazel test //:release-validate-deps --test_output=streamed
  deployment:
    deploy-github:
      image: graknlabs-ubuntu-20.04
      filter:
        owner: graknlabs
        branch: master
      command: |
        pyenv install -s 3.6.10
        pyenv global 3.6.10 system
        pip install certifi
        export RELEASE_NOTES_TOKEN=$REPO_GITHUB_TOKEN
        bazel run @graknlabs_dependencies//tool/release:create-notes -- grakn $(cat VERSION) ./RELEASE_TEMPLATE.md
        export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
        bazel run --define version=$(cat VERSION) //:deploy-github -- $GRABL_COMMIT
    deploy-brew:
      image: graknlabs-ubuntu-20.04
      dependencies: [deploy-github]
      filter:
        owner: graknlabs
        branch: master
      command: |
        pyenv install -s 3.6.10
        pyenv global 3.6.10 system
        export DEPLOY_BREW_TOKEN=$REPO_GITHUB_TOKEN
        bazel run --define version=$(cat VERSION) //:deploy-brew -- release
    deploy-apt-release:
      image: graknlabs-ubuntu-20.04
      filter:
        owner: graknlabs
        branch: master
      dependencies: [deploy-github]
      command: |
        pyenv install 3.7.9
        pyenv global 3.7.9
        sudo unlink /usr/bin/python3
        sudo ln -s $(which python3) /usr/bin/python3
        sudo ln -s /usr/share/pyshared/lsb_release.py /opt/pyenv/versions/3.7.9/lib/python3.7/site-packages/lsb_release.py
        export DEPLOY_APT_USERNAME=$REPO_GRAKN_USERNAME
        export DEPLOY_APT_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run --define version=$(cat VERSION) //server:deploy-apt -- release
        bazel run --define version=$(cat VERSION) //:deploy-apt -- release
    #    deploy-rpm-release:
    #      image: graknlabs-ubuntu-20.04
    #      filter:
    #        owner: graknlabs
    #        branch: master
    #      dependencies: [deploy-github]
    #      command: |
    #        export DEPLOY_RPM_USERNAME=$REPO_GRAKN_USERNAME
    #        export DEPLOY_RPM_PASSWORD=$REPO_GRAKN_PASSWORD
    #        bazel run --define version=$(cat VERSION) //server:deploy-rpm -- release
    #        bazel run --define version=$(cat VERSION) //:deploy-rpm -- release
    deploy-docker:
      image: graknlabs-ubuntu-20.04
      filter:
        owner: graknlabs
        branch: master
      dependencies: [deploy-github]
      command: |
        docker login -u $REPO_DOCKER_USERNAME -p $REPO_DOCKER_PASSWORD
        bazel run //:deploy-docker
    deploy-artifact-release:
      image: graknlabs-ubuntu-20.04
      filter:
        owner: graknlabs
        branch: master
      dependencies: [deploy-github]
      command: |
        export DEPLOY_ARTIFACT_USERNAME=$REPO_GRAKN_USERNAME
        export DEPLOY_ARTIFACT_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run --define version=$(cat VERSION) //server:deploy-linux-targz -- release
        bazel run --define version=$(cat VERSION) //server:deploy-mac-zip -- release
        bazel run --define version=$(cat VERSION) //server:deploy-windows-zip -- release
